<template>
  <div id="about" class="bg-primary-dark feature-img-section pt90 pb90">
    <div class="container">
      <div class="row">
        <div class="col-sm-12">
          <h2 class="text-white text-center">About Us</h2>
          <p class="text-white-gray row align-items-center" id="musicHead" contenteditable="false">
            Here in the puppy lounge, we like to consider ourselves as an open format room where you could listen to
            whatever you feel like listening to. Although be aware that we do tend to lean towards a few genres so don't be surprised when you come into the lounge and we are playing the following genres:
          </p>

          <ul
            class="list-inline text-center feature-list text-white-gray"
            id="musicHead"
            contenteditable="false"
          >
            <b>
              <!--Todo: populate these genres from last.fm -->
              <li id="musicBody" contenteditable="false">Rap</li>
              <li id="musicBody" contenteditable="false">Hip-Hop</li>
              <li id="musicBody" contenteditable="false">R&B</li>
              <li id="musicBody" contenteditable="false">Deep House</li>
              <li id="musicBody" contenteditable="false">Nu-Disco</li>
              <li id="musicBody" contenteditable="false">Trap</li>
              <li id="musicBody" contenteditable="false">Funk</li>
              <li id="musicBody" contenteditable="false">Dubstep</li>
              <li id="musicBody" contenteditable="false">Indie</li>
              <li id="musicBody" contenteditable="false">Latin</li>
              <li id="musicBody" contenteditable="false">Americana</li>
            </b>
          </ul>

          <p class="text-center">
            If you are curious and want a little taste of what we listen to, check out one of our weekly playlists. They contain about 199 of the highest rated songs from the past week.
            The playlist is auto-generated by the team over at JQBX, but know that the music was originally curated by the puppers in the lounge.
          </p>

          <div class="spotify-container">
            <iframe
              class="spotify-embed"
              src="https://open.spotify.com/embed/playlist/4bWrI10vRCD0zzZ54E7w2N"
              width="60%"
              height="280"
              frameborder="0"
              allowtransparency="true"
              allow="encrypted-media"
            ></iframe>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: "about-section",
  props: {},
  data() {
    return {};
  },
  methods: {}
};
</script>

<style lang="scss">
.spotify-container {
  display: flex;
  align-content: center;
  justify-content: center;
  .spotify-embed {
    margin: 2rem 0;
    max-width: 60%;
  }
}
</style>
